schema: "classroom50/repo-config/v1"
classroom: "ds112"
assignment: "portfolio"
owner:
  username: "lliu1-coder"
  id: 326907206
  accepted_at: "2026-09-11T02:09:30Z"
source:
  owner: "mac-ds112-f26"
  owner_id: 323651608
  repo: "portfolio-template"
  branch: "main"
